[package]
name = "cosmic-noodle"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
directories = "5.0"
iced = { version = "0.12.1", features = ["advanced", "tokio", "canvas"] }
time = "0.3.36"
